[project]
name = "tabpfn-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "catboost>=1.2.10",
    "ipython>=9.15.0",
    "matplotlib>=3.11.0",
    "numpy>=2.5.1",
    "openml>=0.15.1",
    "pandas>=2.3.3",
    "rich>=15.0.0",
    "scikit-learn>=1.9.0",
    "tabpfn>=8.0.8",
    "tabpfn-client>=0.3.2",
    "torch>=2.12.1",
    "xgboost>=3.3.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.1",
]
